version: '3.8'

services:
  api-gateway:
    image: papyrgb/flask-sensor-app:latest
    ports:
      - "5000:5000"
    environment:
      # Changed localhost to database service name for inter-container communication
      - DATABASE_URI=postgresql://postgres:datasql78$$@database:5432/NumericFarm
    networks:
      - app-network
    user: "1000:1000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  data-processing-service:
    image: papyrgb/data-processing-service:latest
    environment:
      - DATABASE_URI=postgresql://postgres:datasql78$$@database:5432/NumericFarm
    networks:
      - app-network
    user: "1000:1000"
    restart: always

  dashboard:
    image: papyrgb/dashboard-sensor-app:latest
    ports:
      - "3000:80"
    networks:
      - app-network
    user: "1000:1000"
    restart: always

  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=NumericFarm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=datasql78$$
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
