apiVersion: v1
kind: Pod
metadata:
  name: mon-pod
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '8080'
spec:
  containers:
  - name: mon-container
    image: mon-image
