apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processing-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-processing
  template:
    metadata:
      labels:
        app: data-processing
    spec:
      containers:
      - name: data-processing
        image: data-processing-image:latest
        ports:
        - containerPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anomaly-detection-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anomaly-detection
  template:
    metadata:
      labels:
        app: anomaly-detection
    spec:
      containers:
      - name: anomaly-detection
        image: anomaly-detection-image:latest
        ports:
        - containerPort: 5002
