apiVersion: v1
kind: Service
metadata:
  name: data-processing-service
spec:
  selector:
    app: data-processing
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: anomaly-detection-service
spec:
  selector:
    app: anomaly-detection
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5002
